const tribeMap = {
  yoruba: "africa",
  igbo: "africa",
  hausa: "africa",
  efik: "africa",
  zulu: "africa",
  xhosa: "africa",
  maasai: "africa",
  berber: "africa",
  fulani: "africa",
  ashanti: "africa",
  tuareg: "africa",
  apache: "americas",
  navajo: "americas",
  inuit: "americas",
  mapuche: "americas",
  quechua: "americas",
  arawak: "americas",
  viking: "europe",
  norsemen: "europe",
  sami: "europe",
  celtic: "europe",
  basque: "europe",
  mongol: "asia",
  tibetan: "asia",
  uyghur: "asia",
  ainu: "asia",
  kazakh: "asia",
  pashtun: "asia",
  aboriginal: "oceania",
  maori: "oceania",
  torresstraitislander: "oceania",
};
export default tribeMap;
